### ISSUE TITLE
New updates?

### ISSUE THREAD

**Issue by Z3r0byte** [Tieso2001/Colony-Clicker#11]
I have dedicated many hours to this early-access game. But I feel like the developer just ran away with my money and isn't going to publish any updates. This makes me very sad and I am wondering if this is actually the case. It's too late for a refund now, so I guess buying this game was just one of my many mistakes.

Hope to hear from you,
Dissatisfied customer

**Comment by Tieso2001** [comment]
Dear Customer of Colony Clicker,

I, the developer of this great and very ambiguous project called Colony Clicker, have not forgotten about you and all the other supporters of this project. I am here to inform you and all others that I have not abandoned this project, but I have taken a break to brainstorm on further ideas for the new update. More details on this will be revealed rather sooner than later. I would like to thank you and all other supporters for playing my game.

- Tieso2001

**Comment by Z3r0byte** [comment]
Thank you for your answer. But if you don't get any updates within a month, I know where you live. Just saying 🤷🏻‍♂️
